### PR TITLE
User Profile added questions and tags

### LINKED ISSUE #61: [Frontend]: Improve the Users Page
- Show the questions asked by the user.
- Show tags

### PR DESCRIPTION
**Pull request by abhijain2003**
Added questions and tags box on user profile page ui please merge it under hacktoberfest 2022

### CODE REVIEW

**Comment by Mayank0255** [comment]
@abhijain2003 
Actually it doesn't look like I expected.

It should look like this or better if possible
image

**Comment by abhijain2003** [comment]
ok just give me some time i'll try it

**Comment by Mayank0255** [comment]
@abhijain2003 what happened, you closed the PR?
Should I unassign the task to you?

**Comment by abhijain2003** [comment]
Ya I won't be able to do sorry man

**Pull request closed without merging**
