### PR TITLE
feat(#23): Making the app responsive

### PR DESCRIPTION
**Pull request by di10**
This PR addresses to issue #23

### CODE REVIEW

**Comment by Mayank0255** [comment]
Can you please add some screenshots of the page in different screen sizes?

Would make my job easier to review it

**Comment by di10** [comment]
### Homepage
localhost_3000_ (2)
localhost_3000_ (1)
localhost_3000_
localhost_3000_ (4)
localhost_3000_ (3)

**Comment by di10** [comment]
### Register
localhost_3000_
localhost_3000_ (1)

**Comment by Mayank0255** [comment]
Good work👍

I have some points that needs to be worked on still-

1. Add some data(like posts with different tags and creating some more users) and then try out the responsiveness

2. The sidebar should go all the way down

3. After adding the data you will be required to make the tags page, users page, single tag page, profile page, Post page and Postform page also responsive.

Note - while adding a question add only one tag not more than that as multiple tags are not functional right now.

@di10 All the best for the task and kudos to you for the work you have done till now

**Comment by di10** [comment]
### Homepage
localhost_3000
localhost_3000_

**Comment by di10** [comment]
### Postform page
localhost_3000_ (1)
localhost_3000_

**Comment by di10** [comment]
### Tags Page
localhost_3000_ (1)
localhost_3000_

**Comment by di10** [comment]
### Single Tag Page
localhost_3000_ (1)
localhost_3000_

**Comment by di10** [comment]
### Post Page
localhost_3000_ (1)
localhost_3000_

**Comment by di10** [comment]
### Users Page
localhost_3000_ (1)
localhost_3000_

**Comment by di10** [comment]
### Profile Page
localhost_3000_ (2)
localhost_3000_

**Comment by Mayank0255** [comment]
@di10 Everything seems good apart from some things -

1. Action buttons such as `Search Button` and `Menu Button` on click should come on top for better traversal as currently they coming in the bottom of the page which is not a good practice.

2. In the `PostForm` page remove the image which is near the title "Ask a question" when the media query reduces such that it does not overlaps with the text.

**Comment by Mayank0255** [comment]
@di10 One more thing that I have committed on the master branch so pull from the upstream and then move forward with the work

**Comment by Mayank0255** [comment]
@di10 Let me know if you are working on this or not, as I will have to close the pr then.

**Comment by Mayank0255** [comment]
@di10 

Create a new PR and reference this one too in that when you have made any progress with the work

**Pull request closed without merging**
